### PR TITLE
Activate IP routing

### PR DESCRIPTION
**Pull request by macjl**
Allow Tailscale to act as an exit node, and route subnets.

### CODE REVIEW

**Comment by kwindrem** [comment]
Is there a reason you'd want to route other IP traffic through a GX device? This takes away CPU cycles for a system that is beginning to show signs of overload or at least sluggishness without this addition.

I have tried adding lines to a run script like you have done and had issues but can't remember exactly what they were. I seem to remember something about logging.

**Comment by macjl** [comment]
I use the Venus Device to route IP subnets, and access it out from boat. For example, with that feature, I can show my NMEA data from home.

As my Venus device is a Raspberry pi 4, I don’t have CPU problems. But I can understand this could be more difficult on a real GX device. Maybe it could just be an option for users who needs it ?

If you don’t want to include it, I will include it in rc.local for my own needs.

**Comment by kwindrem** [comment]
Understood.

I think it's best to add a user preference for this and add it to the menu and let TailScaleGX-control handle the switching.

FYI, Victron has plans to integrate tailscale into Venus OS natively. When this happens, my TailscaleGX package will become obsolete.

**Comment by kwindrem** [comment]
I'm having an issue with implementing this. After I made the changes to enable and disable IP forwarding, I can no longer access the internet (even a ping) from the GX device with tailscale enabled. I need to delete tailscale's state.

Obviously, enabling IP forwarding is changing the tailscale configuration somehow. Any ideas?

**Comment by macjl** [comment]
I did'nt had any issue on my side. What did you do to "enable and disable IP forwarding" ?

I don't think enabling IP Forwarding changes any parameter in tailscale. It's just a Linux kernel parameter.

After enabling IP forwarding, if you want to enable exit note, you have to pass this command :
`/data/TailscaleGX/tailscale set --advertise-exit-node`
and confirm in your tailscale account this machine is authorized to act as exit node

For network routing, same thing with this command : 
`/data/TailscaleGX/tailscale set --advertise-routes <CIDR_OF_NETWORK>`

**Comment by kwindrem** [comment]
I'm using the sysctl calls you had in your commit and not doing anything in tailscale.

Doing so is definitely changing tailscale somehow because the only way to recover from this is to delete the current state.

I have not done anything in tailscale but will try the advertise things you mention. There needs to be a way back though. Is that an "unset"?

It is not clear to me what needs to be done to make this work for you. If I need to specify parameters with this, I need to know what those are and put them in settings and hook up the UI. Might be approaching the threshold of too much work and complexity for a generic solution.

**Comment by macjl** [comment]
Here are the command to control IP Forwarding : 

Activate IPv4 Forwarding : `sysctl -w net.ipv4.ip_forward=1`
Deactivate IPv4 Forwarding : `sysctl -w net.ipv4.ip_forward=0`
Show current state of IPv4 Forwarding : `sysctl net.ipv4.ip_forward`

Activate IPv6 Forwarding : `sysctl -w net.ipv6.conf.all.forwarding=1`
Deactivate IPv6 Forwarding : `sysctl -w net.ipv6.conf.all.forwarding=0`
Show current state of IPv6 Forwarding : `sysctl net.ipv6.conf.all.forwarding`

I don't understand what's can be changing on tailscale config when doing this...

I would understand you don"t want to implement this if you have issues with it. I have a workaround, so it's not a problem for me. I just wanted to help other people which could have the same needs.

**Comment by kwindrem** [comment]
I tested again today and it with no changes! Ghost in the machine.

For this to work for you do I need to add the advertise-exit-node flag when starting up tailscaled? If so, how would I turn it off (or do I need to)?

What about advertise-routes ???

Thanks for your help

**Comment by macjl** [comment]
Some informations for this Tailscale feature : https://tailscale.com/kb/1019/subnets

**Comment by kwindrem** [comment]
Today I experienced more network connection losses even without enabling IP forwarding or exit-node. Deleting the tailscale state didn't help this time. I reinstalled the firmware and all is well now. Not seeing any problems and traffic through the GX device is working for other devices on the local network. Yea!

I checked in additions to allow IP forwarding and enabling exit-node. It's v1.70.

I did things a different way so don't need your PR

**Comment by macjl** [comment]
Thank you!
I upgraded today the TailscaleGX package on my VenusOS rpi. I had to log the machine again in my Tailscale account, but after that, all went fine. I found the option to activate routing, and it seems to work as expected.

**Comment by kwindrem** [comment]
The need to log in to tailscale again is due to a typo I fixed with v1.7. I'd been storing the tailscale state in the wrong location.

**Pull request closed without merging**
